name: cliente

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          branch: "master"
          heroku_api_key: 'HRKU-cd6eb0d1-fcac-4d8c-84fe-63e7ff699ad1'
          heroku_app_name: "soap-calculator"
          heroku_email: "maximo.98@hotmail.com"
          